
server:
  port: 9092

spring:
  main:
    allow-circular-references: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kwetter_posts?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: kwetter_posts
    password: EqG9*6949@WKb]gi

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL5Dialect

  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin2017

  http:
    converters:
      preferred-json-mapper: gson